// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdjtywfjTHT1swn2GI1SAnbBMDP37ByFE',
    appId: '1:437431578843:web:e21ac7c8458ac575775cfe',
    messagingSenderId: '437431578843',
    projectId: 'wifapp',
    authDomain: 'wifapp.firebaseapp.com',
    storageBucket: 'wifapp.appspot.com',
    measurementId: 'G-17KNCPVHP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK6E22b0CEGld8XShJU0LhtbCZGaHBL2I',
    appId: '1:437431578843:android:ffe0243670a59331775cfe',
    messagingSenderId: '437431578843',
    projectId: 'wifapp',
    storageBucket: 'wifapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATIjkUjP8KCYiOTeoESMVJ9JGV-tAV9Wc',
    appId: '1:437431578843:ios:3d19cfe06cfc9595775cfe',
    messagingSenderId: '437431578843',
    projectId: 'wifapp',
    storageBucket: 'wifapp.appspot.com',
    iosBundleId: 'com.example.wifApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATIjkUjP8KCYiOTeoESMVJ9JGV-tAV9Wc',
    appId: '1:437431578843:ios:936157291e47cdb9775cfe',
    messagingSenderId: '437431578843',
    projectId: 'wifapp',
    storageBucket: 'wifapp.appspot.com',
    iosBundleId: 'com.example.wifApp.RunnerTests',
  );
}
